### ISSUE TITLE
milestone2 approach

### ISSUE THREAD

**Issue by moniquewong** [UBC-MDS/DSCI_522_Group_303#14]
Thoughts after reading milestone2 requirements:

- It may make sense to get the feature processing, machine learning algorithm and production of a table / a figure done on a jupyter notebook before we start touching the scripts
- We should probably get at least a portion of the scripts going before Thursday (I suspect we’re going to have issues here) so that we can ask questions in lab
- Given that timeline, the earliest time I have to work on this is Weds evening / Thurs morning. I’m happy to whichever part of this … but if one of you can take a crack at the jupyter notebooks tuff before then … then I can set up the scripts before lab on Thursday
- Then during the lab on Thursday we can brainstorm what to write / how to structure the report so that we’re done earlier rather than later

To be discussed at team meeting on Tuesday at 1pm

**Comment by trevorkwan** [comment]
Meetings Notes for Today: 

Polina will start today will the scripts for data wrangling and EDA, some processing of the categorical varaibles.

Trevor will take whatever Polina left off on. Deal with missing data, make the pipeline. Try one or two machine learning things and do cross val, maybe output table of things of the things we tried. Try a figure in the proposal. (all should be regressors, not classifiers, random forest regressor, xgb, one hot encode the neighborhoods, test the accuracy of it but can be misleading)

Monique will pick off where Trevor left off and try to stick it into scripts. So by Thursday lab we can check to see if we have any problems.

**Comment by moniquewong** [comment]
@PolinaRomanchenko @trevorkwan 
What remains as of Thursday ~6pm: 
- [x] Update proposal with what we ended up doing
- [ ] On analyze_data.py: add docstrings and test functions for support functions
- [x] Write report with output figures from EDA and analysis scripts
- [x] Add instructions to run the scripts on README.md
- [ ] Create version2.0
- [ ] Submit links

**Comment by moniquewong** [comment]
Remaining tasks on https://github.com/UBC-MDS/DSCI_522_Group_303/issues/33
