### ISSUE TITLE
data_wrangling.R issues

### ISSUE THREAD

**Issue by moniquewong** [UBC-MDS/DSCI_522_Group_303#20]
@PolinaRomanchenko 
Related to [this pull request](https://github.com/UBC-MDS/DSCI_522_Group_303/pull/19)

I got the data_wrangling.R to output the test and train csv but the price variable was coerced to NAs

This is the Terminal command I used:
`Rscript src/data_wrangling.R --data_path data/listings.csv.gz --file_path_train data/training.csv --file_path_test data/test.csv` 

This is the error I got on my Terminal screen on R when I ran it:
Warning messages:
1: In main(opt$data_path, opt$file_path_train, opt$file_path_test) :
  NAs introduced by coercion
2: In main(opt$data_path, opt$file_path_train, opt$file_path_test) :
  NAs introduced by coercion

Do you want to take a crack at fixing it?

**Comment by moniquewong** [comment]
If splitting data is the problem, maybe we should save one wrangled file (a csv with just the features we're using) and go back to Python for splitting 

Just a thought....

@PolinaRomanchenko @trevorkwan 
I'll start off at 7am tomorrow morning at whatever stage the both of you leave off at tonight. So submit the pull requests if you change anything so that we can build off of each other's work and avoid merge conflicts.

**Comment by moniquewong** [comment]
Also found code on how Tiffany did the data preprocessing and splitting in R. Maybe you used this already, but just in case you haven't:
https://github.com/ttimbers/breast_cancer_predictor/blob/master/src/pre_process_wisc.r

**Comment by trevorkwan** [comment]
i've started the preprocessing and feature selection in a jupyter notebook "analysis" under the analysis folder

**Comment by PolinaRomanchenko** [comment]
I thought that we have to split it. Because in the next scripts we're not supposed to use test data at all.
