### ISSUE TITLE
v3 or v4 for altair to run analyze_data.py

### ISSUE THREAD

**Issue by trevorkwan** [UBC-MDS/DSCI_522_Group_303#48]
hey team, are you all on vegalite v3 or v4? i am unable to run analyze_data.py because the assert statement checks for v3, and i have v4 altair. can we all upgrade to v4 altair so we can change that assert statement?

**Comment by trevorkwan** [comment]
i am now trying to run analyze_data.py after changing it to v4, will update when i see if it works.

**Comment by trevorkwan** [comment]
after changing the assert statement for test_fit_and_plot_best_model() to v4 ("assert isinstance(residual_plot, alt.vegalite.v4.api.Chart), "residual_plot is not altair chart object"), the tests work and I am able to fully run the Makefile. We could consider putting in the usage instructions to tell users to have the latest Altair version.

**Comment by moniquewong** [comment]
I'm trying to write an assert statement that would be version agnostic by using `alt.Chart` instead
